# Generated by Django 4.2.4 on 2023-10-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apppedidosnow",
            "0010_rename_titulo_bairro_nome_remove_bairro_preco_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Motoboy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, default=0, max_length=100, null=True),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
