# Generated by Django 4.2.4 on 2023-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apppedidosnow", "0011_motoboy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.CharField(blank=True, default=0, max_length=10, null=True),
                ),
                (
                    "nome",
                    models.CharField(blank=True, default=0, max_length=100, null=True),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.IntegerField(
                choices=[(1, "PRODUCAO"), (2, "Pronto"), (3, "Pago")], default=1
            ),
        ),
    ]
